## [project]
project_id = "kzycwqjcqcmenlwswhnf"

[db]
port = 54322

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]

[auth]
site_url = "https://haulinlogs.github.io/LawnBudAI/"
additional_redirect_urls = ["http://localhost:3000", "https://haulinlogs.github.io/LawnBudAI/*"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false

[analytics]
enabled = true
